### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by JostMigenda** [JostMigenda/sntools#16]
Various minor documentation improvements, as suggested by @benjaminrose in [this post](https://github.com/openjournals/joss-reviews/issues/2877#issuecomment-742051700) in the JOSS review.

- [x] Make clear(er) that sntools is a command line app.
- [x] Compiled version of documentation.
- [x] First example should run more quickly.
- [x] Simplify arguments of first example

**Comment by benjaminrose** [comment]
@JostMigenda, I like the current example becuase it shows many `sntools` options. I would keep it along side an improved first run experience.

**Comment by JostMigenda** [comment]
@benjaminrose Perhaps it’s best to have two separate examples—an introductory one (that’s very quick and uses few optional arguments for clarity), and a more advanced example (that can run for longer and demonstrate many common arguments)?

E.g. `sntools fluxes/intp2001.data --format nakazato --endtime 50` as an introduction (that runs in ~15 s on my machine) and `sntools fluxes/intp1301.data --format nakazato --ordering normal --distance 20 --detector SuperK --verbose`

**Comment by JostMigenda** [comment]
Regarding compiled version of the LaTeX documentation:
I’ve uploaded a pdf file to release v0.7 and [have added an action](https://github.com/JostMigenda/sntools/commit/8ffcb516ae57f7996f7018ad535f48db1e963be1) that should automatically generate a pdf file for every new release and attach it.

**Comment by benjaminrose** [comment]
Sounds great!

**Comment by JostMigenda** [comment]
I’ve [updated the examples](https://github.com/JostMigenda/sntools/pull/18/commits/5d43ac10f4cf565d622e52ab796d692a186b1f40) as discussed, though I decided to use `--channel es` instead of `--ordering normal` for the second one: That makes the output shorter and easier to explain because it’s only simulating 4 channel/flavour combinations (instead of 14 for normal mass ordering and all channels).

Also [noted explicitly](https://github.com/JostMigenda/sntools/pull/18/commits/48a9614675d56bcf6a8f717a163c7851bd2bdc49) that it’s a command line app.

After those commits, I think #18 covers all the requested documentation improvements and I will merge it soon if there are no additional comments.
