### ISSUE TITLE
Packaging improvements

### ISSUE THREAD

**Issue by JostMigenda** [JostMigenda/sntools#19]
Prompted by @benjaminrose’s suggestions in [this comment](https://github.com/openjournals/joss-reviews/issues/2877#issuecomment-742051700) on the JOSS review:

> Tests don't install the package via pip. They currently test the source code, good. But don't test what will be sent installed from pypi, less good. This explains how you are testing your project directory and not how it will be installed by users, https://hynek.me/articles/testing-packaging/. This is a valid test suite, but may not be doing what you expect.

Some background:
Since I didn’t have experience with Python packaging before working on sntools, I tried to stick close to the official recommendations ([1](https://packaging.python.org/guides/distributing-packages-using-setuptools/#your-package), [2](https://packaging.python.org/tutorials/packaging-projects/#creating-the-package-files)), which did not mention the `src` folder structure recommended in the linked blog post. (Though now that I’ve looked into it, it seems to me that this is [hotly debated](https://github.com/pypa/packaging.python.org/issues/320).)

I think my first step to improve packaging should be to set up a GitHub Action that automatically packages sntools and publishes it to PyPI whenever there’s a new release. (That will largely eliminate human error, which is probably the main source of packaging issues.) I’ll check how it’s possible to install & test as part of that action and will update this issue accordingly.

**Comment by benjaminrose** [comment]
Yes, this is a hotly debated topic. As such it should not hold up the acceptance to JOSS, but it is something to understand and document. Code always does what you say rather than what you intend.

**Comment by JostMigenda** [comment]
I’ve [added an action](https://github.com/JostMigenda/sntools/commit/ca1f22b1390aeb06e1c37169d9aa87f340667208) to package up any new release and publish it to PyPI. Made a new release (v0.7.1) a few hours ago to test this and it appears to work well. This action will largely eliminate the possibility of human error & will work without modification for typical changes to sntools (i.e. new detectors, input formats, etc.).

I’ve made a private note to revisit this if there are major changes to the structure of sntools & will also leave this issue open for visibility.
